FROM centos
LABEL Name="Task1"
RUN yum install vim wget -y



FROM myimage
LABEL Name="Docker"
RUN yum install git -y

#python:
print("Enter a Name")
Name = input()
print("Hello", Name)

FROM python:3
WORKDIR /usr/src/app
COPY . .
ENTRYPOINT python3 test.py

FROM python:3
WORKDIR /usr/src/app
COPY . .
ENTRYPOINT echo "Hellow world"

FROM python:3
ENTRYPOINT ["/bin/echo", "python3"]
CMD ["test.py"]


FROM ubuntu:16.04
MAINTAINER Babu
RUN apt-get update
RUN apt-get install wget openssh-server -y
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN echo 'root:root123' | chpasswd
RUN mkdir /var/run/sshd
CMD ["/usr/sbin/sshd", "-D"]
EXPOSE 22