- hosts: all
  remote_user: ec2-user
  become : yes
  vars:
    tomcat_port: 9090
  tasks:
  - name: updating yum package
    yum:
      name: "*"
      state: latest
  - name: install java 8
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Download tomcat
    get_url:
      url: https://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.45/bin/apache-tomcat-9.0.45.tar.gz
      dest: /opt
      mode: '0777'
  - name: Unzip our tar file
    unarchive:
      src: /opt/apache-tomcat-9.0.45.tar.gz
      dest: /opt
      remote_src: yes
      mode: '0777'
  - name: Templating a server.xml
    template:
       src: server.xml.j2
       dest: /opt/apache-tomcat-9.0.45/conf/server.xml
       mode: '0777'
  - name: stoping tomcat
    shell: nohup /opt/apache-tomcat-9.0.45/bin/shutdown.sh &
  - name: starting tomcat
    shell: nohup /opt/apache-tomcat-9.0.45/bin/startup.sh &
- name: Download Tocat
  get_url:
    url: https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
    dest: /opt/apache-tomcat-9.0.45/webapps
    mode: '0777'

